### ISSUE TITLE
Unable to generate HONO + OH <=> N(O)(O)[O] in R_Addition_MultipleBond

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-database#145]
Running a nitrogen sim in RMG without defining reaction libraries (testing rate rules) resulted with an error (one of many):
```
Error: Unable to calculate degeneracy for reaction <Molecule "ON=O"> + <Molecule "[OH]"> <=> <Molecule "N(O)(O)[O]"> in reaction family R_Addition_MultipleBond. Expected 1 reaction but generated 0
Reactant: <Molecule "ON=O">
Reactant: <Molecule "[OH]">
Product: <Molecule "N(O)(O)[O]">
Traceback (most recent call last):
  File "C:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1367, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False))
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1587, in __generateReactions
    reaction.degeneracy = self.calculateDegeneracy(reaction)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1386, in calculateDegeneracy
    return reactions[0].degeneracy
IndexError: list index out of range

Traceback (most recent call last):
  File "C:\Code\RMG-Py/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 533, in execute
    bimolecularReact=self.bimolecularReact)
  File "C:\Code\RMG-Py\rmgpy\rmg\model.py", line 621, in enlarge
    rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bimolecularReact)
  File "C:\Code\RMG-Py\rmgpy\rmg\react.py", line 155, in reactAll
    rxns = list(react(*spcTuples))
  File "C:\Code\RMG-Py\rmgpy\rmg\react.py", line 75, in react
    combos
  File "C:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "C:\Anaconda\envs\rmg_env\lib\site-packages\scoop-0.7.2.0-py2.7.egg\scoop\fallbacks.py", line 49, in wrapper
  File "C:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1367, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False))
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1587, in __generateReactions
    reaction.degeneracy = self.calculateDegeneracy(reaction)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1386, in calculateDegeneracy
    return reactions[0].degeneracy
IndexError: list index out of range
```

It fits the R_Addition_MultipleBond family, yet no reaction was generated.
![1](https://cloud.githubusercontent.com/assets/16158262/20124786/0c1abc10-a5f7-11e6-9795-f20aa425862a.png) + ![2](https://cloud.githubusercontent.com/assets/16158262/20124794/14c922e8-a5f7-11e6-8bb2-615d817863d1.png) <=> ![3](https://cloud.githubusercontent.com/assets/16158262/20124800/1c4652fc-a5f7-11e6-96b5-43e2d2406290.png)

 Searching for `ON=O` and `OH` in the kinetics search brings up only the addition reaction of the OH group to the O atom, not N. This is strange, since the right groups for the above reaction exist in this reaction family: `N3d-NonDe_Od` for `ON=O`, and `OJ_pri` for `OH`.

**Comment by alongd** [comment]
Adding a rate rule with an exact match to R_Add_MulBond still resulted in the same error. The error message is "unable to calculate degeneracy ... Expected 1 reaction but generated 0". It is unclear to me why no reaction was generated in the degeneracy calculation.

**Comment by alongd** [comment]
This was caused due to inappropriate (too tight) species contains in the input file (see [RMG issue 602](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/602)). Solved by increasing the maximum allowed oxygen atoms to 3 or above.
