### ISSUE TITLE
NetworkError: Unexpected type of path reaction (specifically related to Cdd_Od-N3d in R_Addition_MultipleBond)

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-database#150]
I got the following trace (also related to [RMGPy 577](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/577)):
```
Traceback (most recent call last):
  File "C:\Code\RMG-Py/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 603, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "C:\Code\RMG-Py\rmgpy\rmg\model.py", line 675, in enlarge
    self.updateUnimolecularReactionNetworks()
  File "C:\Code\RMG-Py\rmgpy\rmg\model.py", line 1471, in updateUnimolecularReactionNetworks
    network.update(self, self.pressureDependence)
  File "C:\Code\RMG-Py\rmgpy\rmg\pdep.py", line 561, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 317, in setConditions
    self.calculateMicrocanonicalRates()
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 569, in calculateMicrocanonicalRates
    raise NetworkError('Unexpected type of path reaction "{0}"'.format(rxn))
rmgpy.pdep.network.NetworkError: Unexpected type of path reaction "HNCO(74) + H(5) <=> C(=N)[O](180)"
```
The reaction is `N=C=O + H <=> N=C[O]`, and the reaction site here should be `Cdd_Od-N3d` (no such group is yet defined under the R_Add_MulBond family, though). While this group should be added, it currently falls under the more general group `Cdd_Od`, but no rate rules are defined for the latter.

**Comment by alongd** [comment]
Rate estimation is available for this reaction using averaging for rate rule `Cd_R;HJ`.
(Average of [Cdd_Od;HJ + CO_O;HJ + Cdd_Sd;HJ + Cds_Cdd;HJ + Cdd_Cds;HJ + Cds_Sd;HJ + Cds_Nd;HJ + Cds_Cds;HJ] Estimated using an average for rate rule [Cd_R;HJ]).
While it's a good idea to add more specific groups and training reactions, estimating the kinetics isn't the source for the above error.

**Comment by alongd** [comment]
This is obviously (now to me as well...) not a database issue, and will be dealt in [RMG-Py issue 577](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/577).
