### ISSUE TITLE
Reaction libraries error: too many values to unpack

### ISSUE THREAD

**Issue by PWstmrlnd** [ReactionMechanismGenerator/RMG-database#75]
When I tried running input.py with reaction libraries (reactionLibraries = ['ERC-FoundationFuelv0.9']), I got the error:

Traceback (most recent call last):
  File "/Users/phillipwestmoreland/anaconda/bin/rmg.py", line 147, in <module>
    rmg.execute(args)
  File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 462, in execute
    self.initialize(args)
  File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 354, in initialize
    self.loadDatabase()
  File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 276, in loadDatabase
    reactionLibraries = [library for library, option in self.reactionLibraries],
ValueError: too many values to unpack

When I took out 'ERC-FoundationFuelv0.9', it ran okay.

**Comment by rwest** [comment]
My fault. Told you the wrong syntax. Check http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#reaction-libraries

Need [("LibraryName",False)]


Richard

On Aug 18, 2015, at 5:31 PM, PWstmrlnd <notifications@github.com<mailto:notifications@github.com>> wrote:


When I tried running input.py with reaction libraries (reactionLibraries = ['ERC-FoundationFuelv0.9']), I got the error:

Traceback (most recent call last):
File "/Users/phillipwestmoreland/anaconda/bin/rmg.py", line 147, in
rmg.execute(args)
File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 462, in execute
self.initialize(args)
File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 354, in initialize
self.loadDatabase()
File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 276, in loadDatabase
reactionLibraries = [library for library, option in self.reactionLibraries],
ValueError: too many values to unpack

When I took out 'ERC-FoundationFuelv0.9', it ran okay.

-

**Comment by nyee** [comment]
Presumably solved.
