### ISSUE TITLE
 got an unexpected keyword argument 'rank'

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-database#94]
I updated to the RMG-database version 724c086d26e5e50ee5221a126639cc07b3c72f2d (running RMG v1.0.3), and now all my runs crash while loading the thermo group database:
```
Loading thermodynamics library from thermo_DFT_CCSDTF12_BAC.py in /home/alongd/ws/RMG-database/input/thermo/libraries...
Loading thermodynamics library from CHN.py in /home/alongd/ws/RMG-database/input/thermo/libraries...
Loading thermodynamics library from DFT_QCI_thermo.py in /home/alongd/ws/RMG-database/input/thermo/libraries...
Loading thermodynamics library from primaryThermoLibrary.py in /home/alongd/ws/RMG-database/input/thermo/libraries...
Loading thermodynamics library from 1Cu4.py in /home/alongd/ws/RMG-database/input/thermo/libraries...
Loading thermodynamics group database from /home/alongd/ws/RMG-database/input/thermo/groups...
Error: Error while reading database '/home/alongd/ws/RMG-database/input/thermo/groups/ring.py'.
Traceback (most recent call last):
  File "/home/alongd/ws/RMG-Py/rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/main.py", line 514, in execute
    self.initialize(inputFile, output_directory, **kwargs)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/main.py", line 380, in initialize
    self.loadDatabase()
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/main.py", line 303, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "/home/alongd/ws/RMG-Py/rmgpy/data/rmg.py", line 94, in load
    self.loadThermo(os.path.join(path, 'thermo'), thermoLibraries, depository)
  File "/home/alongd/ws/RMG-Py/rmgpy/data/rmg.py", line 114, in loadThermo
    self.thermo.load(path, thermoLibraries, depository)
  File "/home/alongd/ws/RMG-Py/rmgpy/data/thermo.py", line 382, in load
    self.loadGroups(os.path.join(path, 'groups'))
  File "/home/alongd/ws/RMG-Py/rmgpy/data/thermo.py", line 422, in loadGroups
    self.groups['ring']    =    ThermoGroups(label='ring').load(os.path.join(path, 'ring.py'   ), self.local_context, self.global_context)
  File "/home/alongd/ws/RMG-Py/rmgpy/data/base.py", line 230, in load
    exec f in global_context, local_context
  File "/home/alongd/ws/RMG-database/input/thermo/groups/ring.py", line 27, in <module>
    rank = 10,
TypeError: loadEntry() got an unexpected keyword argument 'rank'
```

**Comment by alongd** [comment]
Error's gone when reverting to the stable RMG-database v1.0.2

**Comment by alongd** [comment]
Now running smoothly with RMG-database 724c086d26e5e50ee5221a126639cc07b3c72f2d and RMG-Py 16767d6111ca4c11717ad6067af2749bcc2be3cf.
I guess this simply was a mismatch between RMG-Py and RMG-database.

**Comment by alongd** [comment]
Should RMG print a message that a minimal version of RMG-database is recommended for the 'current' RMG-Py?
